- name: Check git is present
  command: which git
  changed_when: no

- name: Clone repository
  ansible.builtin.git:
    repo: "{{ wcs_git_url }}"
    dest: "{{ wcs_src_dir }}"
    version: 2.8.0
    clone: yes
    update: yes
  notify: restart ha

- name: Create custom_components directory
  ansible.builtin.file:
    path: "{{ ha_custom_components_dir }}"
    state: directory
    mode: "0755"

- name: Install to custom_components directory
  ansible.builtin.copy:
    src: "{{ wcs_src_dir }}/custom_components/waste_collection_schedule/"
    dest: "{{ ha_custom_components_dir }}/waste_collection_schedule"
    remote_src: yes
    mode: "0755"
  notify: restart ha
