DOMAIN = "energy_cost_forecast"

PLATFORMS = ["sensor", "number", "select"]

CONF_NAME = "name"
CONF_IMPORT_RATE_SENSOR = "import_rate_sensor"
CONF_EXPORT_RATE_SENSOR = "export_rate_sensor"
CONF_EXPORT_POWER_SENSOR = "export_power_sensor"
CONF_PROFILE = "power_profile"
CONF_PROFILE_FILE = "profile_file"
CONF_PROFILE_SENSOR = "power_profile_sensor"
CONF_MAX_COST_PERCENTILE = "max_cost_percentile"
CONF_START_STEP_MINUTES = "start_step_minutes"
CONF_START_STEP_MODE = "start_step_mode"
CONF_UPDATE_INTERVAL_MINUTES = "update_interval_minutes"

ATTR_COSTS = "costs"
ATTR_PROFILE = "profile"
ATTR_PROFILE_INPUT = "profile_input"
ATTR_PROFILE_SOURCE = "profile_source"
ATTR_PROFILE_ERROR = "profile_error"
ATTR_RATE_SOURCE = "rate_source"

DATA_MAX_COST_PERCENTILE = "max_cost_percentile"
DATA_START_STEP_MINUTES = "start_step_minutes"
DATA_START_STEP_MODE = "start_step_mode"

DEFAULT_MAX_COST_PERCENTILE = 0.0
DEFAULT_START_STEP_MINUTES = 30
DEFAULT_UPDATE_INTERVAL_MINUTES = 15

START_MODE_RATE_CHANGES_KEY = "rate-changes"
START_MODE_FIXED_INTERVAL_KEY = "fixed-interval"
START_MODE_RATE_CHANGES_LABEL = "Rate changes"
START_MODE_FIXED_INTERVAL_LABEL = "Fixed interval"
START_MODE_OPTIONS = [START_MODE_RATE_CHANGES_LABEL, START_MODE_FIXED_INTERVAL_LABEL]
START_MODE_KEY_TO_LABEL = {
    START_MODE_RATE_CHANGES_KEY: START_MODE_RATE_CHANGES_LABEL,
    START_MODE_FIXED_INTERVAL_KEY: START_MODE_FIXED_INTERVAL_LABEL,
}
START_MODE_LABEL_TO_KEY = {value: key for key, value in START_MODE_KEY_TO_LABEL.items()}
DEFAULT_START_MODE = START_MODE_RATE_CHANGES_LABEL
