sensor:
  - name: Car Battery Energy Current
    unique_id: car_battery_energy_current
    state_class: measurement
    unit_of_measurement: kWh
    state: >-
      {% set capacity = states('input_number.car_battery_energy_capacity') | float(0) %}
      {% set level_current = states('sensor.car_battery_level') | float(0) %}
      {{ (capacity * level_current / 100) | round(3) }}
    availability: >-
      {{
        states('input_number.car_battery_energy_capacity')
          not in ['unknown', 'unavailable', 'none']
        and states('sensor.car_battery_level')
          not in ['unknown', 'unavailable', 'none']
      }}

  - name: Car Battery Energy Needed
    unique_id: car_battery_energy_needed
    state_class: measurement
    unit_of_measurement: kWh
    state: >-
      {% set target = states('input_number.car_battery_energy_target') | float(0) %}
      {% set current = states('sensor.car_battery_energy_current') | float(0) %}
      {{ [target - current, 0] | max | round(3) }}
    availability: >-
      {{
        states('input_number.car_battery_energy_target')
          not in ['unknown', 'unavailable', 'none']
        and states('sensor.car_battery_energy_current')
          not in ['unknown', 'unavailable', 'none']
      }}

  - name: Car Battery Charge Power Profile
    unique_id: car_battery_charge_power_profile
    state: >-
      {% set energy_needed = states('sensor.car_battery_energy_needed') | float(0) %}
      {% if energy_needed <= 0 %}
        {{ [[0, '1m']] | tojson }}
      {% else %}
        {% set minutes = (energy_needed / 2.3 * 60) | round(0) | int %}
        {% if minutes < 1 %}
          {% set minutes = 1 %}
        {% endif %}
        {{ [[2300, minutes ~ 'm']] | tojson }}
      {% endif %}
    availability: >-
      {{
        states('sensor.car_battery_energy_needed')
          not in ['unknown', 'unavailable', 'none']
      }}

  - name: Car Battery Off Peak Charge Cost
    unique_id: car_battery_off_peak_charge_cost
    device_class: monetary
    state_class: total
    unit_of_measurement: GBP
    state: >-
      {% set energy_needed = states('sensor.car_battery_energy_needed') | float(0) %}
      {% set rates_raw = state_attr('sensor.octopus_energy_electricity_21l4421345_2700007165105_fused_day_rates', 'rates') %}
      {% if rates_raw is string %}
        {% set rates = rates_raw | from_json %}
      {% else %}
        {% set rates = rates_raw | default([], true) %}
      {% endif %}
      {% set ns = namespace(values=[]) %}
      {% for rate in rates %}
        {% if rate.value_inc_vat is defined %}
          {% set ns.values = ns.values + [rate.value_inc_vat] %}
        {% elif rate.value is defined %}
          {% set ns.values = ns.values + [rate.value] %}
        {% endif %}
      {% endfor %}
      {% if ns.values %}
        {{ (energy_needed * (ns.values | min)) | round(2) }}
      {% else %}
        {{ none }}
      {% endif %}
    availability: >-
      {{
        states('sensor.car_battery_energy_needed')
          not in ['unknown', 'unavailable', 'none']
        and state_attr('sensor.octopus_energy_electricity_21l4421345_2700007165105_fused_day_rates', 'rates')
          not in [None, 'unknown', 'unavailable', 'none', '']
      }}
