sensor:
  - name: Connor's Desk Socket Power
    unique_id: connors_desk_socket_power
    device_class: power
    unit_of_measurement: W
    state: "{{ state_attr('switch.connors_desk_socket', 'current_consumption') }}"
    availability: >-
      {{
        state_attr('switch.connors_desk_socket', 'current_consumption')
          not in [None, 'unknown', 'unavailable']
      }}
