sensor:
  - unique_id: dishwasher_socket_power
    name: Dishwasher Socket Power
    device_class: power
    unit_of_measurement: W
    state: "{{ states.switch.dishwasher_socket.attributes.current_consumption }}"
