sensor:
  - name: Fridge Socket Power
    unique_id: fridge_socket_power
    device_class: power
    unit_of_measurement: W
    state: "{{ state_attr('switch.fridge_socket', 'current_consumption') }}"
    availability: >-
      {{
        state_attr('switch.fridge_socket', 'current_consumption')
          not in [None, 'unknown', 'unavailable']
      }}
