sensor:
  - unique_id: fridge_socket_power
    name: Fridge Socket Power
    device_class: power
    unit_of_measurement: W
    state: "{{ states.switch.fridge_socket.attributes.current_consumption }}"
