sensor:
  # Convert actual irrigation volume to rainfall equivalent to be used in irrigation
  # decision.
  - name: Lawn Irrigation Rainfall Equivalent Total
    unit_of_measurement: "cm"
    state: >
      {% set volume = states('sensor.lawn_irrigation_volume_total') | float(0) %}
      {% set area = states('input_number.lawn_size') | float(0) %}
      {{ (volume / area * 100) | round(2) }}

  # 1) Seasonal frequency
  - name: "Lawn Irrigation Frequency"
    # id: lawn_irrigation_frequency
    state: >
      {% set m = now().month %}
      {% if m in [3,4,5] %}    1    {# Spring #}
      {% elif m == 6 %}        2    {# Early Summer #}
      {% elif m in [7,8] %}    3    {# Summer #}
      {% elif m == 9 %}        2    {# Late Summer #}
      {% elif m in [10,11] %}  1    {# Fall #}
      {% else %}               0    {# Winter #}
      {% endif %}
    icon: mdi:calendar-range

  # 2) Which weekdays to water
  - name: "Lawn Irrigation Days"
    # id: lawn_irrigation_days
    state: >
      {% set plan = {
         0: [],
         1: ['tue'],
         2: ['sun','thu'],
         3: ['sun','tue','thu']
      } %}
      {{ plan[states('sensor.lawn_irrigation_frequency')|int] | join(',') }}
    icon: mdi:calendar-check

  # 3) Do we need to water today?
  - name: "Lawn Irrigation Today"
    # id: lawn_irrigation_today
    state: >
      {% set thresh = states('input_number.lawn_irrigation_rain_threshold')|float %}
      {% set p = states('sensor.home_precip_accumulation_0d')|default(0)|float %}
      {% set days = states('sensor.lawn_irrigation_days').split(',') %}
      {% set today = now().strftime('%a').lower() %}
      {{ 'yes' if (today in days and p < thresh) else 'no' }}
    icon: mdi:watering-can
    attributes:
      threshold_cm: "{{ states('input_number.lawn_irrigation_rain_threshold') }}"
      forecast_cm: >
        {{ states('sensor.home_precip_accumulation_0d')|default(0) }}
