sensor:
  # Convert actual irrigation volume to rainfall equivalent to be used in irrigation
  # decision.
  - name: Lawn Irrigation Rainfall Equivalent Total
    unit_of_measurement: "cm"
    state: >
      {% set volume = states('sensor.lawn_irrigation_volume_total') %}
      {% set area = states('input_number.lawn_size') %}
      {% if volume in ['unknown', 'unavailable', None]
         or area in ['unknown', 'unavailable', None]
         or area | float == 0
      %}
        unavailable
      {% else %}
          {% set volume = volume | float(0) %}
          {% set area = area | float(0) %}
          (volume / area * 100) | round(2)
      {% endif %}

  # Actual plus forecast rainfall in a 7-day bracket around today.
  - name: Lawn Irrigation Rainfall Equivalent Last/Forecast 7 Days
    unit_of_measurement: "cm"
    icon: mdi:rain
    state: >
      {{
        (states('sensor.lawn_irrigation_rainfall_equivalent_last_7_days')|float(0)) +
        (states('sensor.7_day_rainfall_forecast')|float(0))
      }}
