sensor:
  - name: Washing Machine Socket Power
    unique_id: washing_machine_socket_power
    device_class: power
    unit_of_measurement: W
    state: "{{ state_attr('switch.washing_machine_socket', 'current_consumption') }}"
    availability: >-
      {{
        state_attr('switch.washing_machine_socket', 'current_consumption')
          not in [None, 'unknown', 'unavailable']
      }}
