binary_sensor:
  - name: Waste Collection Schedule Update Available
    unique_id: waste_collection_schedule_update_available
    device_class: update
    state: >-
      {% set installed = states('sensor.waste_collection_schedule_installed_version') %}
      {% set latest = states('sensor.waste_collection_schedule_latest_release') %}
      {{
        installed not in ['unknown', 'unavailable', None]
          and latest not in ['unknown', 'unavailable', None]
          and installed != latest
      }}
    attributes:
      installed_version: "{{ states('sensor.waste_collection_schedule_installed_version') }}"
      latest_version: "{{ states('sensor.waste_collection_schedule_latest_release') }}"
