- hosts: homeassistant
  tasks:
    - name: copy python requirements.txt to appdaemon apps
      ansible.builtin.copy:
        src: requirements.txt
        dest: "{{ appdaemon_dir }}/apps/"
      register: requirements
# TODO: Hangs trying to install
#    - name: install python requirements to system
#      ansible.builtin.pip:
#        requirements: "{{ appdaemon_dir }}/apps/requirements.txt"
#        extra_args: --break-system-packages
#      when: requirements.changed
    - name: install appdaemon modules
      ansible.builtin.copy:
        src: "modules/{{ module }}.py"
        dest: "{{ appdaemon_dir }}/apps/{{ module }}.py"
      loop:
        - bindicator
      loop_control:
        loop_var: module
    - name: configure appdaemon apps
      ansible.builtin.template:
        src: apps.yaml.j2
        dest: "{{ appdaemon_dir }}/apps/apps.yaml"
      vars:
        apps:
          - name: bindicator
            module: bindicator
            class: App
