- hosts: homeassistant
  tasks:
    # TODO: Restart appropriate parts of homeassistant according to what has changed
    - name: install components
      ansible.builtin.synchronize:
        src: "../../components/{{ component }}/{{ component }}"
        dest: "{{ config_dir }}/custom_components/"
        recursive: yes
        delete: yes
      loop:
        - bindicator
      loop_control:
        loop_var: component
    - name: remove default automations file
      file:
        dest: "{{ config_dir }}/automations.yaml"
        state: absent
    - name: install automations dir
      ansible.builtin.synchronize:
        src: "automations"
        dest: "{{ config_dir }}"
        recursive: yes
        delete: yes
    - name: install configuration
      copy:
        src: configuration.yaml
        dest: "{{ config_dir }}/configuration.yaml"
