- alias: Close covers when solar output is high
  description: >
    Close covers to when solar output is consistently high. Only close covers which are
    not already closed more than the solar close position.

  trigger:
    - platform: numeric_state
      entity_id: sensor.solar_generation_meter_power_consumption
      above: 1500
      for: "00:05:00"

  action:
    - variables:
        close_position: 20

        # List of covers to close. Only select those that are not already closed more than
        # the solar close position.
        close_covers: >
          {{ expand('group.covers')
             | selectattr('attributes.current_position', 'gt', close_position)
             | map(attribute='entity_id')
             | list
          }}

        # Read already closed covers
        previous_closed: >
          {{ states('input_text.covers_closed_by_solar') | from_json }}

        # Read current positions of covers to be closed
        extra_closed: >-
          {% set R = {} %}
          {% for cover in close_covers %}
            {% set R = R | combine({ (cover): (state_attr(cover, 'current_position') | int) }) %}
          {% endfor %}
          {{ R }}

        # Merge
        updated_closed: >
          {{ previous_closed | combine(extra_closed) }}

    # Close the covers
    - service: cover.set_cover_position
      target:
        entity_id: "{{ close_covers }}"
      data:
        position: "{{ close_position }}"

    # Write back updated closed covers
    - service: input_text.set_value
      data:
        entity_id: input_text.covers_closed_by_solar
        value: "{{ updated_closed | tojson }}"
