alias: Open blinds to 80% at 9am
trigger:
  - platform: time
    at: "09:00:00"
condition:
  - condition: state
    entity_id: input_boolean.covers_closed_by_solar
    state: "off"
action:
  - service: cover.set_cover_position
    target:
      entity_id: group.covers
    data:
      position: 80
