alias: Close blinds when solar output is high
description: Closes covers when solar generation exceeds threshold for more than 5 minutes
trigger:
  - platform: numeric_state
    entity_id: sensor.solar_generation_meter_power_consumption
    above: 1500
    for: "00:05:00"
action:
  - service: cover.set_cover_position
    target:
      entity_id: group.covers
    data:
      position: 10
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.covers_closed_by_solar
