id: letsencrypt
alias: Renew Let's Encrypt Certificates
description: Run the Let's Encrypt add-on every Saturday at 03:00 AM
trigger:
  - platform: time
    at: '03:00:00'
condition:
  - condition: time
    weekday:
      - sat
action:
  - service: hassio.addon_start
    data:
      addon: core_letsencrypt
mode: single
