alias: 'Turn on microwave when pantry door opens'
trigger:
  - platform: state
    entity_id: binary_sensor.pantry_door
    to: 'on'
action:
  - service: switch.turn_on
    target:
      entity_id: switch.microwave_socket
